sudo: required
dist: trusty

language: ruby

env:
  - DB=postgres

gemfile:
  - gemfiles/spree_3_2.gemfile
  - gemfiles/spree_3_5.gemfile
  - gemfiles/spree_3_6.gemfile
  - gemfiles/spree_master.gemfile

script:
  - bundle exec rake test_app
  - rails db:setup
  - bundle exec rake spec

rvm:
  - 2.5.1
  - 2.4.2
  - 2.3.1

matrix:
  allow_failures:
    - gemfile: gemfiles/spree_master.gemfile
